export const memoryData = [
  { title: "Day 1", description: "The day everything changed. I still remember how my heart felt when you replied." },
  { title: "Day 2", description: "We started sharing memes and laughs — our little language of love." },
  { title: "Day 3", description: "I asked for your Steam, pretending it was casual... but I just wanted to be closer." },
  { title: "Day 4", description: "You called me 'gift boyfriend,' and suddenly I felt like I could fly." },
  { title: "Day 5", description: "We fell asleep texting. Even in dreams, you’re with me." },
  { title: "Day 6", description: "You sent that reel about oranges — and I swear it made me want to be the other half." },
  { title: "Day 7", description: "I asked if you wanted to play Valo. Honestly? I just wanted to hear your voice." },
  { title: "Day 8", description: "That jumpscare reaction you had still makes me laugh — you’re so cute." },
  { title: "Day 9", description: "You sent me music. Every lyric felt like something I’d write about you." },
  { title: "Day 10", description: "Mwahh messages, sleepy emojis, heart reacts — all the little things that made my day." },
  { title: "Day 11", description: "I missed you today. A lot. Even though we talked, it wasn’t enough." },
  { title: "Day 12", description: "You told me I could always count on you. I haven’t forgotten that." },
  { title: "Day 13", description: "We started calling each other bb. It still makes me smile every time." },
  { title: "Day 14", description: "You made me feel safe just by being kind. I needed that more than I admitted." },
  { title: "Day 15", description: "Good morning messages from you are sunshine through my screen." },
  { title: "Day 16", description: "You’re the only person who can make me laugh through a meme and cry with a message." },
  { title: "Day 17", description: "I love how you care. Deeply, without needing to be asked." },
  { title: "Day 18", description: "The way you texted ‘Mwah’ like 6 times in a row? I saved that." },
  { title: "Day 19", description: "Sometimes you send nothing but an emoji — and I feel everything." },
  { title: "Day 20", description: "You once said 'I trust you' — and I’ve tried every day to be worthy of it." },
  { title: "Day 21", description: "I started counting days just to see how far we've come." },
  { title: "Day 22", description: "You sent a sleepy selfie and I stared at it for too long. You're beautiful." },
  { title: "Day 23", description: "We didn't say much today, but you still made me feel loved." },
  { title: "Day 24", description: "You asked if I ate. That simple care made me feel like your world." },
  { title: "Day 25", description: "Your sleepy 'je t’aime' means more than poetry." },
  { title: "Day 26", description: "When you say 'sbaaah nour' — it’s like a blessing." },
  { title: "Day 27", description: "You’re patient with me, even when I overthink everything." },
  { title: "Day 28", description: "You called me your love. Again. I don’t take that for granted." },
  { title: "Day 29", description: "You said I’m your peace. You’re mine too." },
  { title: "Day 30", description: "I dream about meeting you for real. It’s the only goal on my list." },
  { title: "Day 31", description: "30 days in — a whole month. And every day, I fell deeper." },
  { title: "Day 32", description: "You reminded me to drink water. Babe, you're love and hydration." },
  { title: "Day 33", description: "We talked about our future like it’s already happening." },
  { title: "Day 34", description: "Even on your bad days, you never fail to ask about mine." },
  { title: "Day 35", description: "I caught myself re-reading old messages. Just to feel you close." },
  { title: "Day 36", description: "You told me ‘no stress’ — and I swear, my shoulders dropped instantly." },
  { title: "Day 37", description: "You call me ‘mon amour’ and I’m yours. Entirely." },
  { title: "Day 38", description: "We laughed so much today. It felt like we were in the same room." },
  { title: "Day 39", description: "You sent a reel with ‘this is us’ — and you were right." },
  { title: "Day 40", description: "You told me to take care of myself. I’m trying, for you." },
  { title: "Day 41", description: "You called me out, gently. I needed it. You make me better." },
  { title: "Day 42", description: "You said you're proud of me. That meant everything." },
  { title: "Day 43", description: "We talked about stupid things today. But with you, nothing’s ever really stupid." },
  { title: "Day 44", description: "You said you missed me. But honestly? I missed you more." },
  { title: "Day 45", description: "You light up my day — even when my screen is off." },
  { title: "Day 46", description: "I keep looking forward to our calls like it’s my favorite part of life." },
  { title: "Day 47", description: "Some days are just emojis. But they still carry love." },
  { title: "Day 48", description: "You noticed I was down — even through text. That’s real love." },
  { title: "Day 49", description: "Your voice on a call? Feels like music written just for me." },
  { title: "Day 50", description: "We argued. But we healed. That’s what makes this real." },
  { title: "Day 51", description: "You said sorry even when you didn’t need to. That’s how I know you care." },
  { title: "Day 52", description: "I promise to be better — for you, for us." },
  { title: "Day 53", description: "You saw the worst of me, and stayed." },
  { title: "Day 54", description: "50 days. Halfway to 100. All of them with you." },
  { title: "Day 55", description: "I trust you more than I trust time." },
  { title: "Day 56", description: "You're the first thing I check in the morning, and the last at night." },
  { title: "Day 57", description: "You showed up for me in small ways. I see it. I feel it." },
  { title: "Day 58", description: "You told me ‘I’m here for you’. You are. Always." },
  { title: "Day 59", description: "You’re my comfort. Even when the world isn’t." },
  { title: "Day 60", description: "Your love has rhythm. Even your silence feels warm." },
  { title: "Day 61", description: "I’d wait a thousand days for you. But I’m grateful it’s just a few more." },
  { title: "Day 62", description: "We don’t just share memes — we share moments." },
  { title: "Day 63", description: "I wish I could teleport to you. Just for a kiss." },
  { title: "Day 64", description: "Your honesty, even when it's hard, makes me love you more." },
  { title: "Day 65", description: "You believe in me. Even when I don’t." },
  { title: "Day 66", description: "I want to cook for you one day — and laugh when I burn the rice." },
  { title: "Day 67", description: "Your presence in my life is like air — quiet, constant, needed." },
  { title: "Day 68", description: "I’d rather text you than go out. Every time." },
  { title: "Day 69", description: "Your ‘I love you’ still feels like a new song." },
  { title: "Day 70", description: "We talk about random stuff — and it still feels intimate." },
  { title: "Day 71", description: "You’re the best part of my digital life." },
  { title: "Day 72", description: "You're the reason my notifications make me smile." },
  { title: "Day 73", description: "One day, these texts will be memories. Until then, they’re lifelines." },
  { title: "Day 74", description: "I never feel alone with you — even when I am." },
  { title: "Day 75", description: "You're proof that connection doesn’t need touch." },
  { title: "Day 76", description: "We built this bond on words — and it’s unbreakable." },
  { title: "Day 77", description: "Our emojis are inside jokes now." },
  { title: "Day 78", description: "Even your ‘ok’ feels like ‘I love you’ to me." },
  { title: "Day 79", description: "75 days. My heart is full." },
  { title: "Day 80", description: "Sometimes I reread your good night texts. They still warm me." },
  { title: "Day 81", description: "You're my favorite distraction." },
  { title: "Day 82", description: "You listened — really listened. I won’t forget that." },
  { title: "Day 83", description: "I get nervous before our calls. I still want to impress you." },
  { title: "Day 84", description: "You're my favorite ‘ping’." },
  { title: "Day 85", description: "Even when I mess up, you show me love." },
  { title: "Day 86", description: "You bring out the softest version of me." },
  { title: "Day 87", description: "You're patient with my flaws. That’s rare." },
  { title: "Day 88", description: "We watched something together today. It was digital, but felt real." },
  { title: "Day 89", description: "You love me on my lazy days. That’s real love." },
  { title: "Day 90", description: "I feel like myself when I talk to you." },
  { title: "Day 91", description: "I told you something scary today. You held it gently." },
  { title: "Day 92", description: "You said you miss my energy. I miss giving it to you." },
  { title: "Day 93", description: "You never ask for much — just for me to be present." },
  { title: "Day 94", description: "Your ‘bonne nuit’ texts are lullabies." },
  { title: "Day 95", description: "Your existence makes mine better." },
  { title: "Day 96", description: "When I say I love you, know it’s layered with truth." },
  { title: "Day 97", description: "You're not just in my life — you're a part of my story." },
  { title: "Day 98", description: "90 days of us. And still, I want more." },
  { title: "Day 99", description: "I love the way you text like you speak — with heart." },
  { title: "Day 100", description: "You showed me love doesn’t need physical presence." },
];